// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hcbybueoufsejvywjcdv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhjYnlidWVvdWZzZWp2eXdqY2R2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc5MDc0NTAsImV4cCI6MjA3MzQ4MzQ1MH0.2u6WHfg8xLy7q1eys8XMygg5NHlNCtkt_5Awi_g10Ww";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});